//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IzyMarketingMailerLog
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campaigns
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Campaigns()
        {
            this.Images = new HashSet<Images>();
            this.Segments = new HashSet<Segments>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Subject { get; set; }
        public bool WasSent { get; set; }
        public string Template { get; set; }
        public string HtmlContent { get; set; }
        public string PathImages { get; set; }
        public int CompanyId { get; set; }
        public int TotalSent { get; set; }
        public Nullable<long> SenderId { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> SentDate { get; set; }
        public string MailerKey { get; set; }
    
        public virtual Campaigns Campaigns1 { get; set; }
        public virtual Campaigns Campaigns2 { get; set; }
        public virtual Companies Companies { get; set; }
        public virtual Senders Senders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Images> Images { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Segments> Segments { get; set; }
    }
}
