//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IzyMarketingMailerLog
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompositionSegments
    {
        public long Id { get; set; }
        public string Tag { get; set; }
        public int Rule { get; set; }
        public string Content { get; set; }
        public int Order { get; set; }
        public int Type { get; set; }
        public long SegmentId { get; set; }
    
        public virtual Segments Segments { get; set; }
    }
}
