//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IzyMarketingMailerLog
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventMetrics
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EventMetrics()
        {
            this.EventMetricDetails = new HashSet<EventMetricDetails>();
        }
    
        public long Id { get; set; }
        public System.DateTime DateEvent { get; set; }
        public string Campaign { get; set; }
        public string TypeEvent { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventMetricDetails> EventMetricDetails { get; set; }
    }
}
