//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IzyMarketingMailerLog
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventMetricDetails
    {
        public long Id { get; set; }
        public string Key { get; set; }
        public string Value { get; set; }
        public long EventMetricId { get; set; }
    
        public virtual EventMetrics EventMetrics { get; set; }
    }
}
