//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IzyMarketingMailerLog
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventMetricSingles
    {
        public long Id { get; set; }
        public string Email { get; set; }
        public string TimeStamp { get; set; }
        public string SmtpId { get; set; }
        public string Event { get; set; }
        public string Category { get; set; }
        public string SgEventId { get; set; }
        public string SgMessageId { get; set; }
        public string UserAgent { get; set; }
        public string Ip { get; set; }
        public string Url { get; set; }
        public string AsmGroupId { get; set; }
        public string CampaignId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Reason { get; set; }
        public string Type { get; set; }
    }
}
