//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IzyMarketingMailerLog
{
    using System;
    using System.Collections.Generic;
    
    public partial class Images
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public long Size { get; set; }
        public Nullable<long> CampaignId { get; set; }
        public string Path { get; set; }
        public Nullable<long> CompanyId { get; set; }
        public Nullable<int> Company_CompanyId { get; set; }
    
        public virtual Campaigns Campaigns { get; set; }
        public virtual Companies Companies { get; set; }
    }
}
