//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IzyMarketingMailerLog
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MailerLogContext : DbContext
    {
        public MailerLogContext()
            : base("name=MailerLogContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<AuditLogDetails> AuditLogDetails { get; set; }
        public virtual DbSet<AuditLogs> AuditLogs { get; set; }
        public virtual DbSet<Campaigns> Campaigns { get; set; }
        public virtual DbSet<Companies> Companies { get; set; }
        public virtual DbSet<CompositionSegments> CompositionSegments { get; set; }
        public virtual DbSet<EmailTestings> EmailTestings { get; set; }
        public virtual DbSet<EventMetricDetails> EventMetricDetails { get; set; }
        public virtual DbSet<EventMetrics> EventMetrics { get; set; }
        public virtual DbSet<EventMetricSingles> EventMetricSingles { get; set; }
        public virtual DbSet<Images> Images { get; set; }
        public virtual DbSet<ListEmailTestings> ListEmailTestings { get; set; }
        public virtual DbSet<RecipientLists> RecipientLists { get; set; }
        public virtual DbSet<Segments> Segments { get; set; }
        public virtual DbSet<Senders> Senders { get; set; }
        public virtual DbSet<Tags> Tags { get; set; }
        public virtual DbSet<Templates> Templates { get; set; }
        public virtual DbSet<UploadedFiles> UploadedFiles { get; set; }
    }
}
