//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IzyMarketingMailerLog
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tags
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public long RecipientListId { get; set; }
    
        public virtual RecipientLists RecipientLists { get; set; }
    }
}
